### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by phoe** [t-sin/lisp-alien-wallpapers#1]
> Because of this wallpapers based on his works, these works should be CC0. (or correct me).

If the original work was released under CC0, it means that the work is free to use for any purpose without any strings attached. If you reuse the work and combine it into something else (e.g. a wallpaper), then the resulting work may be given away under any terms and any license whatsoever.

So, if your wallpapers are CC0 as well, that is permissible, but *not* required from your side. CC0 (public domain) is *not* a viral license.

**Comment by t-sin** [comment]
Thanks and yes, you are right. What I want to say with that is “this project is licensed under CC0 and thanks Conrad Barski” simply.
I’ll change the sentences.

**Comment by t-sin** [comment]
The sentences are fixed at https://github.com/t-sin/lisp-alien-wallpapers/commit/fb2bc52b3f21aa0a92d19b69e44e660d21d0da73

**Comment by phoe** [comment]
Thanks!
